# .github/workflows/create-google-maps-link.yml
name: Create Google Maps Link

on:
  workflow_dispatch:
    inputs:
      address:
        description: "Enter the address to generate the Google Maps link"
        required: true

jobs:
  generate-link:
    runs-on: ubuntu-latest  # Use Ubuntu runner

    steps:
      - name: Generate Google Maps Link
        run: |
          address="${{ github.event.inputs.address }}"
          encoded_address=$(echo "$address" | jq -sRr @uri)
          maps_link="https://www.google.com/maps/search/?api=1&query=$encoded_address"
          echo "Here is your Google Maps link: $maps_link"
