# .github/workflows/create-google-maps-link.yml
name: Create SBDR Jira Ticket with Map Link

on:
  workflow_dispatch:
    inputs:
      address:
        description: "Enter the address to generate the Google Maps link"
        required: true
      tool:
        description: "Select the tool for the task"
        required: true
        type: choice
        options:
          - Chainsaw
          - Mud-Out

jobs:
  generate-ticket:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Google Maps Link
        id: generate_link
        run: |
          address="${{ github.event.inputs.address }}"
          tool="${{ github.event.inputs.tool }}"
          encoded_address=$(echo "$address" | jq -sRr @uri)
          maps_link="https://www.google.com/maps/search/?api=1&query=$encoded_address"
          echo "::set-output name=maps_link::$maps_link"
          echo "::set-output name=address::$address"

      - name: Create Jira Ticket
        id: create_ticket
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_PERSONAL_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_PERSONAL_API_TOKEN }}
          JIRA_EMAIL: ${{ secrets.JIRA_PERSONAL_EMAIL }}
        run: |
          address="${{ steps.generate_link.outputs.address }}"
          tool="${{ github.event.inputs.tool }}"

          issue_data=$(jq -n \
            --arg summary "Address Task: $address" \
            --argjson description '{
              "type": "doc",
              "version": 1,
              "content": [
                {
                  "type": "paragraph",
                  "content": [
                    { "type": "text", "text": "Tool: " },
                    { "type": "text", "text": "'"$tool"'", "marks": [{ "type": "strong" }] }
                  ]
                }
              ]
            }' \
            '{
              fields: {
                project: { key: "SBDRF" },
                summary: $summary,
                description: $description,
                issuetype: { name: "Chainsaw" }
              }
            }')

          response=$(curl -s -X POST \
            --url "$JIRA_BASE_URL/rest/api/3/issue" \
            --user "$JIRA_EMAIL:$JIRA_API_TOKEN" \
            --header 'Content-Type: application/json' \
            --data "$issue_data")

          issue_key=$(echo "$response" | jq -r '.key')
          echo "::set-output name=issue_key::$issue_key"

      - name: Add Google Maps Link to Jira Ticket
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_PERSONAL_BASE_URL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_PERSONAL_API_TOKEN }}
          JIRA_EMAIL: ${{ secrets.JIRA_PERSONAL_EMAIL }}
        run: |
          issue_key="${{ steps.create_ticket.outputs.issue_key }}"
          maps_link="${{ steps.generate_link.outputs.maps_link }}"

          link_data=$(jq -n \
            --arg url "$maps_link" \
            --arg title "Google Maps Location" \
            '{
              "globalId": $url,
              "application": {
                "type": "com.atlassian.jira",
                "name": "Google Maps"
              },
              "relationship": "links to",
              "object": {
                "url": $url,
                "title": $title
              }
            }')

          curl -X POST \
            --url "$JIRA_BASE_URL/rest/api/3/issue/$issue_key/remotelink" \
            --user "$JIRA_EMAIL:$JIRA_API_TOKEN" \
            --header 'Content-Type: application/json' \
            --data "$link_data"
