name: Generate Git Graph

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-git-graph:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Update Node.js to version 18

      - name: Install Dependencies
        run: npm install @gitgraph/js jsdom

      - name: Generate Git Log Graph
        run: git log --graph --oneline --all > git-log-graph.txt

      - name: Create GitGraph SVG
        run: |
          node -e "
          const fs = require('fs');
          const { createGitgraph } = require('@gitgraph/js');
          const jsdom = require('jsdom');
          const { JSDOM } = jsdom;

          const logData = fs.readFileSync('git-log-graph.txt', 'utf8');
          const commitLines = logData.split('\\n');

          // Initialize JSDOM and Gitgraph.js
          const dom = new JSDOM('<!DOCTYPE html><body></body>');
          global.document = dom.window.document;

          const gitgraphContainer = document.createElement('div');
          const gitgraph = createGitgraph(gitgraphContainer, {
            template: 'metro', // You can customize the template
          });

          commitLines.forEach((line) => {
            const [hash, ...messageParts] = line.split(' ');
            const message = messageParts.join(' ');
            gitgraph.commit({
              subject: message,
              hash,
            });
          });

          const svgElement = gitgraphContainer.querySelector('svg');
          const svgContent = svgElement.outerHTML;
          fs.writeFileSync('gitgraph-output.svg', svgContent);
          "

      - name: Upload GitGraph SVG
        uses: actions/upload-artifact@v3
        with:
          name: git-graph
          path: gitgraph-output.svg
