name: Create Jira Ticket

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every week at midnight on Sunday
  workflow_dispatch: # Allows manual trigger

jobs:
  create-ticket:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Read Jira ticket information
        id: read_ticket_info
        run: |
          PROJECT_KEY=$(grep "Project Key:" Data/jiraTicketExample.txt | awk -F': ' '{print $2}')
          SUMMARY=$(grep "Summary:" Data/jiraTicketExample.txt | awk -F': ' '{print $2}')
          echo "PROJECT_KEY=$PROJECT_KEY" >> $GITHUB_ENV
          echo "SUMMARY=$SUMMARY" >> $GITHUB_ENV

      - name: Create Jira ticket
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_PERSONAL_BASE_URL }}
          JIRA_EMAIL: ${{ secrets.JIRA_PERSONAL_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_PERSONAL_API_TOKEN }}
          PROJECT_KEY: ${{ env.PROJECT_KEY }}
          SUMMARY: ${{ env.SUMMARY }}
        run: |
          response=$(curl -s -w "\nHTTP_CODE:%{http_code}" -X POST -H "Content-Type: application/json" \
            -u $JIRA_EMAIL:$JIRA_API_TOKEN \
            --data '{
              "fields": {
                "project": {
                  "key": "'"$PROJECT_KEY"'"
                },
                "summary": "'"$SUMMARY"'",
                "issuetype": {
                  "name": "Task"
                }
              }
            }' $JIRA_BASE_URL/rest/api/2/issue/)
          echo "$response"
          http_code=$(echo "$response" | grep "HTTP_CODE" | awk -F: '{print $2}')
          if [ "$http_code" -ne 201 ]; then
            exit 1
          fi
