name: Fetch Jira Issue

on:
  workflow_dispatch:
    inputs:
      issue_key:
        description: 'Jira Issue Key (e.g., PROJ-123)'
        required: true

jobs:
  fetch-jira-issue:
    runs-on: ubuntu-latest

    env:
      JIRA_BASE_URL: ${{ secrets.JIRA_PERSONAL_BASE_URL }}
      JIRA_EMAIL: ${{ secrets.JIRA_PERSONAL_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_PERSONAL_API_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Fetch Jira Issue
        id: fetch_issue
        run: |
          ISSUE_KEY=${{ github.event.inputs.issue_key }}
          RESPONSE=$(curl -s -u "${JIRA_EMAIL}:${JIRA_API_TOKEN}" \
            -X GET \
            -H "Content-Type: application/json" \
            "${JIRA_BASE_URL}/rest/api/3/issue/${ISSUE_KEY}")

          echo "Response: $RESPONSE"

          # Use environment file to set the output
          echo "jira_response=$RESPONSE" >> $GITHUB_ENV
