name: Delete Done Issues in Jira Manual

on:
  workflow_dispatch:  # This allows the workflow to be triggered manually

jobs:
  delete-issues:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run PowerShell script
      shell: pwsh
      env:
        JIRA_URL: ${{ secrets.JIRA_URL }}
        JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
        JIRA_API: ${{ secrets.JIRA_API }}
      run: ./Atlassian/Issues/Jira-DeleteIssuesStatusDoneInProjectKc.ps1
