name: Secret Scan

on:
  push:
    branches:
      - main
      - 'release/*'
  pull_request:
    branches:
      - main
      - 'release/*'

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Run Gitleaks
      uses: zricethezav/gitleaks-action@v1.3.0
      with:
        args: "--path . --verbose"
